"""Synthetic data generation for development, testing and public demonstration.

Nothing produced here derives from real records. Every synthetic artefact is
labelled as such, and the release built from it carries ``data_origin:
synthetic`` so that documents compiled from it are watermarked.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

from vamengoc.synth.aefi_files import AEFISynthConfig, generate_aefi
from vamengoc.synth.lots_workbook import LotsSynthConfig, SyntheticLots, generate_lots

__all__ = ["SyntheticDataset", "generate_synthetic_dataset"]

MARKER_FILE = "SYNTHETIC_DATA.txt"


@dataclass
class SyntheticDataset:
    directory: Path
    lots: SyntheticLots
    aefi_truth: pd.DataFrame


def generate_synthetic_dataset(
    out_dir: Path,
    *,
    scale: float = 1.0,
    seed: int = 20260930,
    schema_variations: bool = True,
    endotoxin_or_per_sd: float = 1.5,
) -> SyntheticDataset:
    """Generate the full synthetic input set (lot workbook + AEFI workbooks) in ``out_dir``."""
    out_dir.mkdir(parents=True, exist_ok=True)
    lots = generate_lots(LotsSynthConfig(seed=seed + 1), out_dir)
    national = lots.lots[lots.lots["national"]].copy()
    log_e = np.log(national["endotoxin"].astype(float))
    national["z_endotoxin"] = (log_e - log_e.mean()) / log_e.std(ddof=0)
    national = national.drop_duplicates("lot_id")
    truth = generate_aefi(
        AEFISynthConfig(
            scale=scale,
            seed=seed + 2,
            schema_variations=schema_variations,
            national_lots=national,
            endotoxin_log_or_per_sd=float(np.log(endotoxin_or_per_sd)),
        ),
        out_dir,
    )
    (out_dir / MARKER_FILE).write_text(
        "All files in this directory are SYNTHETIC, generated by `vamengoc synth`.\n"
        "They contain no real person, report or lot. Planted effects: "
        f"endotoxin OR per SD on fever>=39 C = {endotoxin_or_per_sd}; process shift in 2018.\n",
        encoding="utf-8",
    )
    return SyntheticDataset(directory=out_dir, lots=lots, aefi_truth=truth)
